### ISSUE TITLE
Markdown parsing with JS+WebView is laggy

### ISSUE THREAD

**Issue by saber-nyan** [LiMium/mini-vector-android#1]
Maybe it's worth using a more native way, for example, [SpannableStringBuilder](https://developer.android.com/reference/android/text/SpannableStringBuilder.html) or a ready-made [Markdown without WebView](https://github.com/noties/Markwon) library?

**Comment by hrj** [comment]
Thanks for the hint!

Though, I wouldn't like this fork to deviate from upstream too much as it will get difficult to maintain. Is there a reason why this can't / won't be done upstream?

In any case, if it doesn't require too many changes I will be happy to merge a PR.

**Comment by saber-nyan** [comment]
> Is there a reason why this can't / won't be done upstream?

No, I created this issue in your repo simply because I'm using your fork.
Also README.md says that this project has already got rid of react-native dependency.

> In any case, if it doesn't require too many changes I will be happy to merge a PR.

I'll try, but I can not guarantee anything 😆

**Comment by hrj** [comment]
If I understand right, `react-native` doesn't use a webview. It compiles down to native, and it was a dependency required by Jitsi. Hence, I could remove both jitsi and react-native in one go.

Would be great if we can get the markdown changes merged with upstream, .. that's what I would do as it would benefit everyone.

**Comment by hrj** [comment]
Closing this, since fixing this upstream will be more favourable. Aside, there are efforts underway to completely rewrite the upstream code. Hence, not much gain in optimising the current code.
