### ISSUE TITLE
Goal of the project

### ISSUE THREAD

**Issue by ghost** [LiMium/mini-vector-android#16]
Hello, I found your app on F-Droid and was curious what the aim is. Is it just the fewer permissions and smaller size?

I was hoping someone would write a Matrix client for non-technical users that creates a password/private key automatically, has a very simple interface akin to most mobile messengers and cut some settings that are not very important to casual users. Automatic registration would also be great and maybe even discoverability through phone number although that sucks for privacy reasons of course. (But the competition is even worse and it would be one way to get them on board with Matrix. Handle the rest later...)

Kind regards

**Comment by hrj** [comment]
Hello!

When creating the project and as of now, the goals have been "fewer permissions" and "improved privacy". ("smaller size" was not a goal but a happy side-effect.)

About a simple messenger; I would be interested too, but I don't have the bandwidth to create one from scratch right now. Maintaining a simplified fork is very challenging so I am ruling that out. If I do find time in the future, it will likely be a separate project from this one.

Thanks for your interest!
