### ISSUE TITLE
Analytics leftovers

### ISSUE THREAD

**Issue by Perelandra0x309** [LiMium/mini-vector-android#24]
exodus-privacy still detects the Firebase tracker in the latest version 0.8.29b:
https://reports.exodus-privacy.eu.org/en/reports/search/com.lavadip.miniVector/

Sometimes that can happen if you have disabled the feature permanently in code but the library definition is still in there somewhere.

**Comment by hrj** [comment]
This might get fixed through this upstream commit: https://github.com/vector-im/riot-android/commit/ea00156e2165ea380beffed88d4e70f872dab3fa

Let's confirm and close in the next release.

**Comment by hrj** [comment]
No trackers are detected in 0.9.1, as per https://reports.exodus-privacy.eu.org/en/reports/76366/
