### ISSUE TITLE
Allow IS that is not responding

### ISSUE THREAD

**Issue by afonari** [LiMium/mini-vector-android#26]
Two IS are hard coded vector.im and riot.im: https://github.com/vector-im/riot-android/blob/047e156cc7f3c708fdcdb4e90c0df63155076bae/vector/src/main/java/im/vector/receiver/VectorRegistrationReceiver.java#L49

Is it possible to allow any host, even localhost? It would fail to connect but that shouldn't prevent using the client. I've tested it by adding both vector.im and riot.im to Blokada blocked hosts.

**Comment by afonari** [comment]
This is what web client shows when IS is set to localhost:
![Screen Shot 2019-07-25 at 7 58 33 PM](https://user-images.githubusercontent.com/1243352/61916483-3c86b000-af38-11e9-89bd-84e0ac9df3a0.png)

**Comment by hrj** [comment]
Sounds like a good idea.

Is it a single line change? (I am not sure of the UI part)

If it's a small change, I can target this for next release. Else, I don't want to diverge too much from upstream.

If you want to raise a PR, please go ahead.

**Comment by afonari** [comment]
> Is it a single line change? (I am not sure of the UI part)

I don't know this for sure.

> If you want to raise a PR, please go ahead.

I've never built an android app. Is there a service that would build per commit and generate an APK that I can test so that I don't need to set up all Android studio, gradle, etc.

**Comment by hrj** [comment]
>  Is there a service that would build per commit and generate an APK that I can test so that I don't need to set up all Android studio, gradle, etc.

I am not aware of any, but you don't need Android studio.

You just need to install JRE and the Android SDK. The build scripts (including gradle launcher) are part of this repository itself. You just need to run:

```
ANDROID_HOME=/path/to/sdk ./gradlew assembleAppDebug
```

The generated APK would be in: `vector/build/outputs//apk/app/debug/vector-app-debug.apk`

**Comment by hrj** [comment]
Just a heads up: the latest commit will not build until @Bubu releases the latest version of Matrix SDK in his repo.

But you can try building with the last release tag: `miniv0.8.29`

**Comment by Bubu** [comment]
Made the sdk release.

**Comment by afonari** [comment]
I have it working for limified-fdroid branch, will create a PR soon.

**Comment by hrj** [comment]
@afonari Cool! The `limified-fdroid` branch was not updated to latest release, until now. I just now merged the latest upstream release (0.9.3) and pushed to both `limified` and `limified-fdroid` branches.

Can you please try again with the latest version?

**Comment by afonari** [comment]
@hrj do you have an ETA for the fdroid release?

**Comment by Bubu** [comment]
Oh, I guess that's on me then? 🤔
