### ISSUE TITLE
Publish FDroid build

### ISSUE THREAD

**Issue by hrj** [LiMium/mini-vector-android#3]
I am not familiar with FDroid build process, but want to support it someday.

Would be glad to get any help on this.

**Comment by Bubu** [comment]
I can help, a few things that need to be done:
* Tagging each release
* Changing appid [here](https://github.com/LiMium/mini-vector-android/blob/limified/vector/build.gradle#L90) -->see #10 

Optional, but I'd prefer having this for an f-droid release:
* forking the sdk and removing the react-native-webrtc dependency there. 
   * this will then greatly cut f-droid build complexity and build-time. because only then we can fully skip building react-native stuff. --> see https://github.com/Bubu/matrix-android-sdk/commit/bca1e18fc171b9c5095b2605c51d2c0d01528e25
* actually removing the jitsi/react aar's from the repo

**Comment by Bubu** [comment]
@hrj How would you like to proceed with the modified sdk dependency (fdroid needs to always build it from source)?

* Do you want to merge + tag mini releases in parallel to mini-vector as well?
* Should I do it (only for the f-droid release)? But I fear that create a little bit too many cross-maintainer dependencies
* Do we want to try to upstream a build flavour that doesn't depend on the react-native-webrtc lib.
  * this is I fear always a bunch more work than just throwing stuff out.

**Comment by hrj** [comment]
@Bubu Thanks!

  * Tagging each release : **Will do; had forgotten to do it for 0.8.7**
  * Changing appid here -->see #10 : **Merged**
  * actually removing the jitsi/react aar's from the repo: **done in `lessAar` branch. Will merge with master soon after we get a fdroid build.**
  * Do you want to merge + tag mini releases in parallel to mini-vector as well?: **I am game for that**

What do you suggest as the next step?

**Comment by hrj** [comment]
I created a WIP MR here : https://gitlab.com/fdroid/fdroiddata/merge_requests/3131

@Bubu I guess you need to add your matrix-sdk fork to the source libraries so that we can reference it in the miniVector build.

**Comment by qazip** [comment]
Any news on this?

**Comment by hrj** [comment]
@Bubu I have released and tagged miniv0.8.15

There is now a branch called `limified-fdroid` which has `jitsi/react` aar's removed and has the battery optimisation permission enabled.

Let me know what else I can do to push this forward.

**Comment by Bubu** [comment]
Updated the MR: https://gitlab.com/fdroid/fdroiddata/merge_requests/3131

Builds fine but, like I said in matrix, I cannot install it in parallel with riot "contains a content provider with the same authority as a provider already installed"

Should that be working?

Also could you give the description another glance if it's still up-to-date?

**Comment by Bubu** [comment]
Found the problem. I think to get this finally out the door I'll set up the build from my fork, hope that's okay.

We should get this consolidated for some future release then.

**Comment by hrj** [comment]
Awesome, thanks!

I have no problem with a build set against your fork. I like the idea behind f-droid and I am happy to extend support as much as I can but, at the moment, I am not a user of f-droid and I don't have the time to maintain that app flavor actively. If you or others send PRs to this repo I will happily merge them.

**Comment by hrj** [comment]
@Bubu has a build working that will be available at https://f-droid.org/packages/com.lavadip.miniVector/

(Currently, there is some f-droid server issue that is blocking it)

**Comment by licaon-kter** [comment]
It's already available ;)
