### ISSUE TITLE
Set all the URLs in config.xml to localhost

### ISSUE THREAD

**Issue by afonari** [LiMium/mini-vector-android#31]
In 0.9.4 bunch of URL have been exposed in https://github.com/LiMium/mini-vector-android/blob/limified/vector/src/main/res/values/config.xml:
```integrations_widgets_urls, integrations_ui_url, etc.```

These defaults point to the proprietary hosts. I propose to change them all to localhost.

What do guys think?

**Comment by hrj** [comment]
How are these URLs used? I have never used integrations myself and just assumed that they have to be explicitly approved by each user that wants to utilise them.
